---
title: "Cherry Blossom Race Data"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(mosaic)
library(ggplot2)
library(pander)



Data_73_21 <- read_csv("Data_73_21.csv", na=c("NR", "NA"), col_types = "ccnccccccn")
Data_22 <- read_csv("Data_22.csv", col_types = "ncccnccccnc", na=c("NR", "NA"))
Data_23 <- read_csv("Data_23.csv", col_types = "ncccnccccnc", na=c("NR", "NA"))
Data_24 <- read_csv("Data_24.csv", col_types = "ncccnccccnc", na=c("NR", "NA"))
```

## Cherry Blossom Race Data 1973-2024

```{r}
Data_73_21 <- Data_73_21 %>% 
  separate(Name, c("Name", "Gender"), sep = -4) %>% 
  mutate(Gender = case_when(Gender == " (M)" ~ "M",
                            Gender == " (W)" ~ "W")) %>% 
  rename(PiS_TiS = `PiS/TiS`, PiD_TiD = `PiD/TiD`) %>% 
  select(1,2,9,7,4,5,6,8,10,11,3) %>% 
  select(-1)

Data_22 <- Data_22 %>% select(-1)
Data_23 <- Data_23 %>% select(-1)
Data_24 <- Data_24 %>% select(-1)

Dat_Comb1 <- rbind(Data_73_21, Data_22, Data_23, Data_24)

```


## Data Cleaning
Included just rows with existing age
```{r}
Dat_Comb <- Dat_Comb1 %>%
  filter(!is.na(Age))

# Process Time and add new columns
Dat_Comb <- Dat_Comb %>%
  mutate(
    Time = na_if(Time, "NR"),          
    Time = na_if(Time, ""),            
    Time = case_when(
      str_detect(Time, "^\\d{1,2}:\\d{1,2}$") ~ paste0("00:", Time), # Add "00:" for missing hours
      str_detect(Time, "^\\d{1,2}:\\d{1,2}:\\d{1,2}$") ~ Time,       
      TRUE ~ NA_character_             # Replace invalid formats with NA
    ),
    Time = hms(Time),                  # Convert valid Time to hms format
    Minutes = period_to_seconds(Time) / 60 # Calculate time in minutes
  ) %>%
  filter(!is.na(Time))                 # Remove rows with missing Time


```

## Adding weatherinfos
```{r}

weather <- read_csv("3865927.csv",show_col_types = FALSE)
dates <- data.frame(
  year = 1973:2024,
  date = as.Date(c("1973-04-01", "1974-03-31", "1975-04-06", "1976-04-04", 
                   "1977-04-03", "1978-04-02", "1979-04-01", "1980-03-30", 
                   "1981-04-05", "1982-04-04", "1983-04-03", "1984-04-01", 
                   "1985-03-31", "1986-04-06", "1987-04-05", "1988-04-03", 
                   "1989-04-02", "1990-04-01", "1991-03-31", "1992-04-05", 
                   "1993-04-04", "1994-04-03", "1995-04-02", "1996-03-31", 
                   "1997-04-06", "1998-04-05", "1999-04-04", "2000-04-02", 
                   "2001-04-01", "2002-04-07", "2003-04-06", "2004-04-04", 
                   "2005-04-03", "2006-04-02", "2007-04-01", "2008-04-06", 
                   "2009-04-05", "2010-04-04", "2011-04-03", "2012-04-01", 
                   "2013-04-07", "2014-04-06", "2015-04-05", "2016-04-03", 
                   "2017-04-02", "2018-04-07", "2019-04-06", "2020-04-05", 
                   "2021-09-12", "2022-04-03", "2023-04-02", "2024-04-6")))

temp<-left_join(Dat_Comb, dates, by = c("Year" = "year"))
Dat_Comb.full <- left_join(temp, select(weather, DATE, PRCP, TMIN), by = c("date" = "DATE"))
```

## Summary Statistics

```{r}
graph1 <- Dat_Comb1 %>%
  group_by(Year) %>%
  add_count() %>%
  ungroup()
  
graph1 %>%  ggplot(aes(x=Year, y=n)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(trans="identity", limits=c(1973,2024), breaks=seq(1973,2024,3)) +
  scale_y_continuous(trans="identity", limits=c(100,18000), 
                     breaks=c(100, 2500,5000,7500,10000,12500,15000,17500)) +
  labs(y="Number of Participants", title="Number of Runners Participating Per Year", 
       caption="Note: 2020 was virtual only and 2021 was pushed to September, both due to Covid-19") +
  theme_bw() +
  theme(plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0), 
       axis.text.x=element_text(angle = 45, hjust = 1))

pander(fav_stats(graph1$n))
```

```{r}
Dat_Comb1 %>% ggplot(aes(x=Year, fill=Gender)) +
  geom_bar(position="fill") +
  scale_fill_manual(values = c("M" = "turquoise", "W" = "salmon")) +
  labs(y="Proportion", title = "Proportion of Men and Women Participating Each Year") +
  geom_abline(aes(intercept=0.5, slope=0), color="black") +
  theme_bw()

graph2 <- Dat_Comb1 %>%
  group_by(Year, Gender) %>% 
  add_count() %>%
  ungroup()

pander(favstats(n ~ Gender, data=graph2))
```

```{r}
graph3 <- Dat_Comb %>% 
  mutate(Age_Group = case_when(
      Age < 20 ~ "Under 20",
      Age >= 20 & Age < 30 ~ "20s",
      Age >= 30 & Age < 40 ~ "30s",
      Age >= 40 & Age < 50 ~ "40s",
      Age >= 50 & Age < 60 ~ "50s",
      Age >= 60 & Age < 70 ~ "60s",
      Age >= 70 ~ "70+"))

graph3 %>% ggplot(aes(x=Year, fill=Age_Group)) +
  geom_bar(position = "stack") +
  labs(y="Number of Participants", 
       title="Number of Runners Participating in Each Age Group Per Year", 
       caption = "Note: 2020 was virtual only and 2021 was pushed to September, both due to Covid-19", fill="Age Group") +
  theme_bw() +
  theme(plot.caption.position = "plot",
        plot.caption = element_text(hjust = 0))
```



## Gender Insights

```{r}
graph4 <- Dat_Comb1 %>% 
  filter(!is.na(Pace)) %>% 
  filter(!is.na(Gender)) %>% 
  mutate(Pace_Num = (period_to_seconds(ms(Pace)))/60) %>% 
  summarise(avg_pace = mean(Pace_Num), .by=c(Gender, Year)) %>% 
  ungroup()

graph4 %>% ggplot(aes(y=avg_pace, x=Year, color=Gender)) +
  geom_line() +
  scale_color_manual(values = c("M" = "turquoise", "W" = "salmon")) +
  scale_x_continuous(trans="identity", limits=c(1973,2024), breaks=seq(1973,2024,3)) +
  labs(y="Average Pace (in Minutes)", title = "Average Pace Each Year by Gender") +
  theme_bw()
pander(favstats(avg_pace ~ Gender, data=graph4))
```


```{r}
Dat_Comb %>% 
  mutate(Pace_Num = (period_to_seconds(ms(Pace)))/60) %>% 
  filter(!is.na(Gender)) %>%
  ggplot(aes(x=Year, y=Pace_Num, group=Year)) +
  scale_x_continuous(trans="identity", limits=c(1973,2024), breaks=seq(1973,2024,3)) +
  geom_boxplot() +
  facet_wrap(~Gender) +
  theme_bw() +
  labs(x="Pace in Minutes", title="Distribution of Pace Each Year by Gender") +
  theme(axis.text.x=element_text(angle = 45, hjust = 1))
```


```{r}
Dat_Comb %>% 
  mutate(Pace_Num = (period_to_seconds(ms(Pace)))/60) %>% 
  filter(!is.na(Gender)) %>%
   mutate(Age_Group = case_when(
      Age < 20 ~ "Under 20",
      Age >= 20 & Age < 30 ~ "20s",
      Age >= 30 & Age < 40 ~ "30s",
      Age >= 40 & Age < 50 ~ "40s",
      Age >= 50 & Age < 60 ~ "50s",
      Age >= 60 & Age < 70 ~ "60s",
      Age >= 70 ~ "70+")) %>% 
  ggplot(aes(x=Gender, y=Age_Group, fill=Pace_Num)) +
  geom_tile()
```



## Was Runners Performance Affected by Weather?
```{r}

avg_per_year <- Dat_Comb.full %>%
  group_by(Year) %>%
  summarise(
    Avg_PRCP = mean(PRCP, na.rm = TRUE),
    winner=min(Minutes, na.rm = TRUE),
    Temperature = mean(TMIN, na.rm = TRUE),
    Minutes = mean(Minutes, na.rm = TRUE)
  )

# Adjusted Plot
ggplot(avg_per_year, aes(x = Year)) +
  # Line for Avg_Pace
  geom_line(aes(y = Minutes, color = "Average Pace (min)"), size = .3) +
  # Line for Avg_PRCP
  geom_line(aes(y = Avg_PRCP * 10, color = "Precipitation (scaled)"), size = 0.3) +
  # Line for Temperature
  geom_line(aes(y = Temperature, color = "Temperature (°F)"), size = 0.3) +
  # Primary and secondary y-axis
  geom_line(aes(y=winner, color="Winner"), size=0.3) +
  scale_y_continuous(
    name = "Pace & Temperature",
    sec.axis = sec_axis(~ . / 10, name = "Precipitation")
  ) +
  # Custom color legend
  scale_color_manual(
    name = "Legend",
    values = c(
      "Average Pace (min)" = "blue",
      "Precipitation (scaled)" = "green",
      "Temperature (°F)" = "red",
      "Winner Time" = "black"
    )
  ) +
  labs(
    title = "Average Time, Precipitation, and Temperature by Year",
    x = "Year"
  ) +
  theme_bw()


avg_per_year
head(Dat_Comb.full)

```



## Regression

```{r}
mod1 <- lm(Minutes ~ Age, data=Dat_Comb)
summary(mod1)

mod2 <- lm(Minutes ~ Age + Gender, data=Dat_Comb)
summary(mod2)

mod3 <- lm(Minutes ~ Age*Gender, data=Dat_Comb)
summary(mod3)
plot(mod3)

Dat_Comb %>% 
  filter(!is.na(Gender)) %>%
  ggplot(aes(x=Age, y=Minutes, color=Gender)) +
  geom_point(alpha=0.1) +
  geom_smooth(method=lm, linewidth=1.2) +
  scale_color_manual(values = c("M" = "turquoise", "W" = "salmon")) +
  labs(y="Run Time in Minutes", title="Predicting Runtime by Age and Gender") +
  theme_bw()
```



